[package]
name = "apollo-client"
version = "0.6.0"
authors = ["jmjoy <918734043@qq.com>"]
edition = "2018"
description = "Rust🦀 client for Apollo."
repository = "https://github.com/jmjoy/apollo-client"
documentation = "https://docs.rs/apollo-client"
license = "Unlicense"
readme = "README.md"
keywords = ["apollo", "client"]
exclude = [
    ".github",
    ".gitignore",
    "sql",
    "docker-compose.yml",
    "test-coverage.sh",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["host-extend"]
host-ip = ["systemstat", "regex"]
host-name = ["hostname"]
host-extend = ["host-ip", "host-name"]
yaml = ["serde_yaml"]
xml = ["serde-xml-rs"]
full = ["yaml", "xml", "host-extend"]

# Internal feature for test suite.
mock-listen = []

[dependencies]
futures = { version = "0.3.1", features = ["alloc"] }
hostname = { version = "0.3.0", optional = true }
http = { package = "http", version = "0.2.0" }
hyper = { version = "0.14", features = ["client", "http1", "tcp"] }
indexmap = { version = "1.6", features = ["serde-1"] }
lazy_static = "1.4.0"
log = "0.4.8"
quick-error = "1.2.2"
regex = { version = "1.3.3", optional = true }
serde = "1.0.104"
serde-xml-rs = { version = "0.3.1", optional = true }
serde_derive = "1.0.104"
serde_json = { version = "1.0.44", features = ["preserve_order"] }
serde_urlencoded = "0.6.1"
serde_yaml = { version = "0.8.11", optional = true }
systemstat = { version = "0.1.5", optional = true }
tokio = { version = "1", features = ["time"] }

[dev-dependencies]
env_logger = "0.8"
tokio = { version = "1", features = ["full"] }
hyper = { version = "0.14", features = ["client", "http1", "server", "tcp"] }

[[example]]
name = "basic"
path = "examples/basic.rs"
required-features = ["host-name"]

[[example]]
name = "listen"
path = "examples/listen.rs"
required-features = ["host-ip", "yaml"]

[[test]]
name = "listen_change"
path = "tests/listen_change.rs"
required-features = ["mock-listen"]

[package.metadata.docs.rs]
features = ["full"]
