[workspace]
members = [
    ".",
    "standalone-apollo-client",
]

[package]
name = "apollo-client"
version = "0.2.0"
authors = ["__JM_Joy__ <918734043@qq.com>"]
edition = "2018"
description = "Rust🦀 client for Apollo."
repository = "https://github.com/jmjoy/apollo-client"
documentation = "https://docs.rs/apollo-client"
license-file = "LICENSE"
readme = "README.md"
keywords = ["apollo", "client"]
exclude = [
    ".github",
    ".gitignore",
    "sql",
    "docker-compose.yml",
    "test-coverage.sh",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = { version = "0.3.1", features = ["alloc"] }
hostname = { version = "0.3.0", optional = true }
http = "0.1.21"
isahc = "0.8.2"
lazy_static = "1.4.0"
log = "0.4.8"
quick-error = "1.2.2"
serde = "1.0.104"
serde-xml-rs = { version = "0.3.1", optional = true }
serde_derive = "1.0.104"
serde_json = "1.0.44"
serde_urlencoded = "0.6.1"
serde_yaml = { version = "0.8.11", optional = true }
systemstat = { version = "0.1.5", optional = true }

[dev-dependencies]
async-std = { version = "1.4.0", features = ["attributes", "unstable"] }
env_logger = "0.7.1"

[features]
default = ["host-ip", "host-name"]
host-ip = ["systemstat"]
host-name = ["hostname"]
yaml = ["serde_yaml"]
xml = ["serde-xml-rs"]
full = ["default", "yaml", "xml"]
