[package]
name = "apollo-client"
version = "0.4.0"
authors = ["__JM_Joy__ <918734043@qq.com>"]
edition = "2018"
description = "Rust🦀 client for Apollo."
repository = "https://github.com/jmjoy/apollo-client"
documentation = "https://docs.rs/apollo-client"
license = "MulanPSL-1.0"
readme = "README.md"
keywords = ["apollo", "client"]
exclude = [
    ".github",
    ".gitignore",
    "sql",
    "docker-compose.yml",
    "test-coverage.sh",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = { version = "0.3.1", features = ["alloc"] }
futures-timer = "2.0.2"
hostname = { version = "0.3.0", optional = true }
http = "0.1.21"
indexmap = { version = "1.3.1", features = ["serde-1"] }
isahc = { version = "0.8.2", default-features = false, features = ["static-curl"] }
lazy_static = "1.4.0"
log = "0.4.8"
quick-error = "1.2.2"
regex = { version = "1.3.3", optional = true }
serde = "1.0.104"
serde-xml-rs = { version = "0.3.1", optional = true }
serde_derive = "1.0.104"
serde_json = { version = "1.0.44", features = ["preserve_order"] }
serde_urlencoded = "0.6.1"
serde_yaml = { version = "0.8.11", optional = true }
systemstat = { version = "0.1.5", optional = true }

[dev-dependencies]
env_logger = "0.7.1"
tokio = { version = "0.2.11", features = ["full"] }

[features]
default = ["host-ip", "host-name"]
host-ip = ["systemstat", "regex"]
host-name = ["hostname"]
yaml = ["serde_yaml"]
xml = ["serde-xml-rs"]
full = ["default", "yaml", "xml"]

[[example]]
name = "basic"
path = "examples/basic.rs"
required-features = ["host-name"]

[[example]]
name = "listen"
path = "examples/listen.rs"
required-features = ["host-ip", "yaml"]

[package.metadata.docs.rs]
features = ["full"]
