[package]
name = "apollo-client"
version = "0.5.0"
authors = ["jmjoy <918734043@qq.com>"]
edition = "2018"
description = "Rust🦀 client for Apollo."
repository = "https://github.com/jmjoy/apollo-client"
documentation = "https://docs.rs/apollo-client"
license = "Unlicense"
readme = "README.md"
keywords = ["apollo", "client"]
exclude = [
    ".github",
    ".gitignore",
    "sql",
    "docker-compose.yml",
    "test-coverage.sh",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["host-extend", "with-curl"]
host-ip = ["systemstat", "regex"]
host-name = ["hostname"]
host-extend = ["host-ip", "host-name"]
yaml = ["serde_yaml"]
xml = ["serde-xml-rs"]
with-curl = ["isahc", "futures-timer", "http-01"]
with-hyper = ["tokio", "hyper", "http-02"]
full-curl = ["with-curl", "yaml", "xml", "host-extend"]
full-hyper = ["with-hyper", "yaml", "xml", "host-extend"]
full = ["full-curl"]

# Internal feature for test suite.
mock-listen = []

[dependencies]
futures = { version = "0.3.1", features = ["alloc"] }
futures-timer = { version = "3.0.2", optional = true }
hostname = { version = "0.3.0", optional = true }
http-01 = { package = "http", version = "0.1.21", optional = true }
http-02 = { package = "http", version = "0.2.0", optional = true }
hyper = { version = "0.13.2", optional = true }
indexmap = { version = "1.3.1", features = ["serde-1"] }
isahc = { version = "0.8.2", default-features = false, features = ["static-curl"], optional = true }
lazy_static = "1.4.0"
log = "0.4.8"
quick-error = "1.2.2"
regex = { version = "1.3.3", optional = true }
serde = "1.0.104"
serde-xml-rs = { version = "0.3.1", optional = true }
serde_derive = "1.0.104"
serde_json = { version = "1.0.44", features = ["preserve_order"] }
serde_urlencoded = "0.6.1"
serde_yaml = { version = "0.8.11", optional = true }
systemstat = { version = "0.1.5", optional = true }
tokio = { version = "0.2.11", features = ["time"], optional = true }

[dev-dependencies]
env_logger = "0.7.1"
futures-timer = "3.0.2"
hyper = "0.13.2"
tokio = { version = "0.2.11", features = ["full"] }

[[example]]
name = "basic"
path = "examples/basic.rs"
required-features = ["host-name"]

[[example]]
name = "scenario"
path = "examples/scenario.rs"
required-features = ["host-ip", "yaml", "with-hyper"]

[[example]]
name = "listen"
path = "examples/listen.rs"
required-features = ["host-ip", "yaml"]

[[test]]
name = "listen_change"
path = "tests/listen_change.rs"
required-features = ["mock-listen"]

[package.metadata.docs.rs]
features = ["full-curl", "full-tokio"]
