[package]
name = "apollo-client"
version = "0.1.0"
authors = ["__JM_Joy__ <918734043@qq.com>"]
edition = "2018"
description = "Rust🦀 client for Apollo."
repository = "https://github.com/jmjoy/apollo-client"
license-file = "LICENSE"
readme = "README.md"
keywords = ["apollo", "client"]
exclude = [
    ".github",
    ".gitignore",
    "sql",
    "docker-compose.yml",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
isahc = "0.8.2"
log = "0.4.8"
quick-error = "1.2.2"
serde = "1.0.104"
serde_derive = "1.0.104"
serde_json = "1.0.44"
