version: '3.6'

services:
  apollo-quick-start:
    image: nobodyiam/apollo-quick-start
    container_name: apollo
    depends_on:
      - apollo-db
    ports:
      - "8080:8080"
      - "8070:8070"
    networks:
      - overlay

  apollo-db:
    image: mysql:5.7
    container_name: apollo-db
    environment:
      TZ: Asia/Shanghai
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - apollo-db-data:/var/lib/mysql
    networks:
      - overlay

volumes:
  apollo-db-data:

networks:
  overlay:
