name: Rust

on:
    push:
      branches:
      - master
      - develop
    pull_request:
      branches:
      - "**"

env:
  RUST_BACKTRACE: 1
  RUST_LOG: apollo_client

jobs:
  bulid-and-test:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        features:
        - ""
        - --no-default-features --features with-curl
        - --no-default-features --features with-hyper
        - --features with-curl
        - --features with-hyper
        - --features xml
        - --features yaml
        - --features full-curl
        - --features full-hyper
        - --all-features
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Docker compose
      run: docker-compose up -d
    - name: Build
      run: cargo build --verbose ${{ matrix.features }}
    - name: Test
      run: cargo test --verbose ${{ matrix.features }}

  check-fmt-and-docs:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: rustup component add rustfmt
        run: rustup component add rustfmt
      - name: fmt
        run: cargo fmt --all -- --check
      - name: doc
        run: cargo doc
