name: Rust

on:
    push:
      branches:
      - master
      - develop
    pull_request:
      branches:
      - master

env:
  RUST_BACKTRACE: 1
  RUST_LOG: apollo_client

jobs:
  bulid-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Docker compose
      run: docker-compose up -d
    - name: Build
      run: cargo build --verbose
    - name: Build with no default features
      run: cargo build --no-default-features --verbose
    - name: Build with feature xml
      run: cargo build --features xml --verbose
    - name: Build with feature yaml
      run: cargo build --features yaml --verbose
    - name: Build with feature full
      run: cargo build --features full --verbose
    - name: Test
      run: cargo test --verbose
    - name: Test with no default features
      run: cargo test --no-default-features --verbose
    - name: Test with feature xml
      run: cargo test --features xml --verbose
    - name: Test with feature yaml
      run: cargo test --features yaml --verbose
    - name: Test with feature full
      run: cargo test --features full --verbose

  check-fmt-and-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: rustup component add rustfmt
        run: rustup component add rustfmt
      - name: fmt
        run: cargo fmt --all -- --check
      - name: doc
        run: cargo doc
